language: python
python:
  - "3.7"
  - "3.9"
# command to install dependencies
cache: pip
install:
  - pip install cython
  - pip install --upgrade pip setuptools wheel
  - pip install .
  - pip install progressbar
  - pip install coveralls
# command to run tests
script:
    - cd tests
    - nosetests --with-coverage --cover-package=pysd
    - coveralls
